### ISSUE TITLE
nzbindex, binsearch: "nice" display names split between name and password field

### ISSUE THREAD

**Issue by maherm** [gboudreau/sabconnectplusplus#120]
I recently often had the problem with downloads I added from nzbindex via 1-click, that the display name is split between name and password. The reason is, that there is a slash (/) in the name, like here:

[207179]-[FULL]-[#a.b.teevee@EFNet]-[ Video.Killed.The.Radio.Star.S05E11.The.Human.League.PDTV.x264-CBFM ]-[01/19] - "video.killed.the.radio.star.s05e11.the.human.league.pdtv.x264-cbfm.par2" yEnc

Everything before the slash lands in the "Name" field, while everything after is in the "Password" field.
I am not familiar with the sabnzbd api, but it seems like this is the way to add files including its password?
I assume this only happens with the few websites, for which "nice names" are offered. You can reproduce the bug on binsearch.info when the query field is empty.
Of yourse you can disable the feature as a workaround, but it would be nice if this would be fixed some time. Especially as Sabnzbd always naturally tries to extract the files with the set (wrong) password first, before trying no password, which consumes unnecassary cpu time and ram.

**Comment by ppslim** [comment]
This is a feature of SAB and not this Chrome extension.

See [here](http://wiki.sabnzbd.org/password-protected-rars)

nzbindex addition is done using the [addurl api](http://wiki.sabnzbd.org/api#toc28) call. sabconnect++ does not provide the NZB filename. This is done by the remote site either by the name of the file, or headers returned by the site.

What SAB then does with it comes down to it's own internal logic.
