### ISSUE TITLE
Adding password for download?

### ISSUE THREAD

**Issue by AzraelCole** [gboudreau/sabconnectplusplus#122]
Hi,

is it possible to set a password (or filename containing the password) for a nzb to download?

Thanks and regards

**Comment by ppslim** [comment]
No, it's not possible to do this gracefully, more so, it's not possible to do for the majority of providers.

SAB supports password protection after an item has entered the queue though, see [here](http://wiki.sabnzbd.org/password-protected-rars)

However the addurl api does not allow you to pick the NZB filename, this is defined by the remote site either by the URL added, or by the headers returned in the HTTP request for the download.
