### ISSUE TITLE
nzbclub integration broken

### ISSUE THREAD

**Issue by monkiibiz** [gboudreau/sabconnectplusplus#129]
After nzbclub.com updated their UI, the SABConnect++ integration is sadly broken - no icon shows up anymore

![image](https://cloud.githubusercontent.com/assets/4595037/8096893/c3eeecdc-0fa1-11e5-8b02-d1583b559f38.png)

**Comment by gboudreau** [comment]
Update sent to Chrome Web Store as 0.6.19

**Comment by Talyrius** [comment]
I always get an 'Empty NZB file' warning when I use the new button.
