### ISSUE TITLE
binsearch integration stopped working

### ISSUE THREAD

**Issue by vanilla-thunder** [gboudreau/sabconnectplusplus#134]
Hello,

seems like binsearch has changed their website.

Earlier you could get nzb file with a GET request to /?action=nzb&*nzbname*=1
But now you need to send a request with POST data "action=nzb&*nzbname*=on" and get nzb file from response attachment.
Basically you need to simulate submitting the original form.

Unfortunately i have no other computer for testing to make sure, that this problem is not caused by my firewall ob adblocker or some other stuff.
Could you check if binsearch still works for you?

In case it doesn't work, i have already tried to fix it and i got some work around but not a final solution.

cheers.

p.s. you prefer space indents and not tab indents, right? i'm preparing a PR with new integration

**Comment by ppslim** [comment]
Integration is still functional for me here and I am using ADP.

Do you get any content if to try and browse to the ?action=nzb&nzbname=1 directly in the browser?

**Comment by vanilla-thunder** [comment]
i'm getting an almost empty nzb file:
<pre><code><?xml version="1.0" encoding="iso-8859-1" ?>
<!DOCTYPE nzb PUBLIC "-//newzBin//DTD NZB 1.0//EN" "http://www.newzbin.com/DTD/nzb/nzb-1.0.dtd">
&lt;!-- NZB Generated by Binsearch.info --&gt;
&lt;nzb xmlns="http://www.newzbin.com/DTD/2003/nzb"&gt;
Post *nzbname* does not exist</pre></code>

i gonna check my browser addons

**Comment by ppslim** [comment]
Did you get anywhere with this?

**Comment by vanilla-thunder** [comment]
sorry, i totally forgot about that.
i had a new antivirus software, which was injecting some stupid code into every pager in every webbrowser. I changed my antivirus and it started working again

**Comment by ppslim** [comment]
Good to hear.
