### ISSUE TITLE
Test Failure when trying to connect to SABnzbd

### ISSUE THREAD

**Issue by Sunslash** [gboudreau/sabconnectplusplus#139]
Hello,
I searched the forum but could not find the answer to this problem, sorry if this is a repost.
I recently had to reinstall Windows, and I cannot access SABnzbd from SABconnect++ ever since.
Both the URL and the API Key are correct, which I verified by using Sickbeard to connect to the same installation of SABnzbd without problems. I also have no trouble accessing SAB by directly writing its IP in Chrome. However, I can't even open SABnzbd using the widget : I get a ERR_FILE_NOT_FOUND error as the extension tries to open chrome-extension://okphadhbbjadcifjplhifajfacbkkbod/192.168.1.3:8080

What could be the cause of this problem ? 

Thanks

**Comment by ppslim** [comment]
Can you direct us on exactly what you are clicking, step by step.

What do you have in the options for your SABnzbd URL?

Is it 192.168.1.3:8080 or http://192.168.1.3:8080/

It should use the full URL format.

**Comment by Sunslash** [comment]
Putting the http:// in front of the address did the trick !

Thank you, I don't I would never have found the solution by myself.

**Comment by ppslim** [comment]
Good to hear.

Sab allows you to host on paths other than / and with SSL, so it makes sense to have the full root URI there.

Good yo hear it's first for you though.
