### ISSUE TITLE
OMGWTFNZBS

### ISSUE THREAD

**Issue by disturbthpce** [gboudreau/sabconnectplusplus#150]
The site OMGWTFNZBS.org has changed TLD. 
Its now OMGWTFNZBZ.me. 

Nothing else has changed so /scrips/content/omgwtfnzbs.js needs to be updated to reflect this.

**Comment by JBFUK** [comment]
Still not fixed...

**Comment by treyturner** [comment]
Relevant PR: https://github.com/gboudreau/sabconnectplusplus/pull/153
