### ISSUE TITLE
No one-click download with drunkenslug.com

### ISSUE THREAD

**Issue by brianjmurrell** [gboudreau/sabconnectplusplus#155]
I'm not getting a 1-click download icon with drunkenslug.com.

I've even added it to the _settings->Providers->1-Click NZB downloading->Newznab Providers (comma-separated list of hostnames)_ configuration item.

**Comment by duostyle** [comment]
Same issue for nzb.su

**Comment by obeyaron** [comment]
same here. if i hover over the sab icon it says https://drunkenslug.com/undefined
Help!

**Comment by gboudreau** [comment]
Should be fixed now; merged a PR from @jdart regarding this. Will be available to Chrome users within an hour.
