### ISSUE TITLE
Problems viewing SABnzbd version: 2.0.1 with SC++

### ISSUE THREAD

**Issue by thorrrr** [gboudreau/sabconnectplusplus#159]
Hi Guys

When i view Sabnzb on server connected no issue but if i try to view on another network PC the page is all broken up
![pageerrors](https://user-images.githubusercontent.com/8170673/27001615-7a9702f8-4dc6-11e7-9e81-64d38e7531c8.jpg)

**Comment by ppslim** [comment]
Just to clarify, you are seeing this problem when browsing Sabnzbd as a normal page in a browser?

If so, you need to report this against the correct project https://github.com/sabnzbd/sabnzbd/

This is the page for sabnzbconnect++, a Chrome extension.

What you seem to be observing is issues with missing style information. Check the developer viewer of your browser (if it has one) when you refresh the page, to see what it is failing to load. The fact you see it specific to another machine, suggest network issues or browser settings problems.

**Comment by thorrrr** [comment]
Yes fixed it now cheers for quick reply
