### ISSUE TITLE
Firefox version?

### ISSUE THREAD

**Issue by mofman** [gboudreau/sabconnectplusplus#168]

**Comment by gboudreau** [comment]
This extension is not actively maintained. Ref: top of README.md file; see https://github.com/gboudreau/sabconnectplusplus/commit/ea093a516fde07ba2f21fd35f12503d5e0855299

https://addons.mozilla.org/en-US/firefox/addon/nzbdstatus/
https://addons.mozilla.org/en-us/firefox/addon/nzbfox/
https://addons.mozilla.org/en-US/firefox/addon/sabnzbdfox/
https://addons.mozilla.org/en-US/firefox/tag/sabnzbd
