### ISSUE TITLE
sabconnect causes yahoo sites to autoscroll

### ISSUE THREAD

**Issue by nxh145** [gboudreau/sabconnectplusplus#169]
this extension causes the yahoo sites and especially the finance page to autoscroll.
I been having this issue since last year.
I finally pinpointed the problem to this extension by enabling and disabling extensions.

**Comment by GrownShapes** [comment]
Same issue with pitchfork.com

**Comment by GrownShapes** [comment]
Same issue with pitchfork.com

**Comment by hopfinity** [comment]
It's not just Yahoo sites.

I just saw it happen here: https://bitcoinist.com/bitcoin-hovers-at-6300-as-bitcoin-cash-soars-and-bitcoin-classic-shuts-down/

And I know I've seen it on a few other sites, though I forget which ones at the moment.

**Comment by datajosh** [comment]
It happens on Hulu too

**Comment by datajosh** [comment]
Potential fix: Under Settings > configuration, disable "Enable Automatic Newznab Detection"

You'll likely have to manually add sites you want it to work on under Settings > providers > Newznab Providers, but it seems to stop the autoscrolling on other sites
