### ISSUE TITLE
Max Speed should be % of maximum line speed not KBps

### ISSUE THREAD

**Issue by coreygo** [gboudreau/sabconnectplusplus#170]
https://github.com/gboudreau/sabconnectplusplus/blob/6435e82f5503f776145e2e7f8d8d72c0f362e4ca/popup.html#L62

![screen shot 2018-06-06 at 8 16 55 pm](https://user-images.githubusercontent.com/649879/41076474-aa779204-69c6-11e8-9eb2-1bdfa5c83523.png)
See: https://sabnzbd.org/wiki/configuration/2.3/general#toc2

**Comment by gboudreau** [comment]
Fixed in #183
