### ISSUE TITLE
bandwidth graph not visible?

### ISSUE THREAD

**Issue by chenks** [gboudreau/sabconnectplusplus#181]
is this extension still in active development?
reason i ask is that i've noticed some functions of the extension stopped working some time ago.
specifically the bandwidth graph, the space is there for it, but no data is shown.

**Comment by gboudreau** [comment]
You can see in the commits log, to assess a repo activity: https://github.com/gboudreau/sabconnectplusplus/commits/master

Personally, I'm not working on this extension anymore. When I receive pull requests, I merge them, and release a new version on the Chrome store, but that's it.

**Comment by chenks** [comment]
i'm not a coder so no idea what the "repo activity" would tell me, all i know is that the graph worked fine, than at some point in the recent past it stopped working.

so maybe a recent pull request has broken it.

**Comment by gboudreau** [comment]
Fixed in #183
