### ISSUE TITLE
Click on Open SABnzbd does not work

### ISSUE THREAD

**Issue by Daimonion1980** [gboudreau/sabconnectplusplus#182]
Hello

After setup my chrome from scratch and installing sabconect++ sometimes it happens that the button "Open Sabnzbd" does not work. 

Together with Issue #181 i have too.

Chome developer console shows some errors, but i douldn't get data from the case when it works.

is there anything i can check what is the problem here?

Chrome version is 80.0.3987.149
Sabconnect++ version is 0.6.29

![Zwischenablagebild (2)](https://user-images.githubusercontent.com/12880413/77225181-2daad880-6b6d-11ea-9aa2-4b20cbaa9324.jpg)

**Comment by Daimonion1980** [comment]
Since last time i didn't change anything but the button works now. 
As you can see from google developer console there are no errors from reDrawPopup, storeRead_popup

![Zwischenablagebild (3)](https://user-images.githubusercontent.com/12880413/77227578-97cd7880-6b81-11ea-8e03-2998ed3d256e.jpg)

Is there a way to analyze hte behavior?

**Comment by gboudreau** [comment]
Fixed in #183

**Comment by Daimonion1980** [comment]
Thnx, perfect! 

Waiting for the Update on Webstore!
