### ISSUE TITLE
sabconnect++ stopped working with omgwtfnzbs

### ISSUE THREAD

**Issue by Darkmensager** [gboudreau/sabconnectplusplus#187]
The icon stopped showing in omgwtfnzbs some days ago. Probably some change in the site that needs an adjustment of sabconnect++ end?

**Comment by omgstaff** [comment]
> The icon stopped showing in omgwtfnzbs some days ago. Probably some change in the site that needs an adjustment of sabconnect++ end?

hi @Darkmensager, 

What appears to be the issue?  Running extension version 0.6.31 from the Chrome web store on Chrome Version 89.0.4389.82 (Official Build) (64-bit) and the "Send to Sab" icon is appearing just fine.

Have you installed any other extensions lately that might be interfering?
Are you running any custom stylesheets that are overlaying websites which might be interfering?

If you can contact us via the website that would be appreciated so we can assist you.

Cheers,
omgstaff

**Comment by omgstaff** [comment]
Fixed in 0.6.32 which has been published to Chrome Web Extension Store.

@gboudreau  we can close out this issue.

**Comment by Darkmensager** [comment]
> Fixed in 0.6.32 which has been published to Chrome Web Extension Store.
> 
> @gboudreau we can close out this issue.

I can confirm its working now. Many thanks.
