### ISSUE TITLE
Sending wrong URL to DogNZB

### ISSUE THREAD

**Issue by TheseUserNamesAreMakingMeThirsty** [gboudreau/sabconnectplusplus#196]
Dog have just updated their servers have a new specific one to handle downloads, this has resulted in a change to the url for NZB grabbing.
Originally it was https://dognzb.cr/fetch/.....
It is now https://dl.dognzb.cr/fetch/......

This results in the following SAB Error; URL Fetching failed; File not on server

**Comment by gboudreau** [comment]
See #195
