### ISSUE TITLE
omgwtfnzbs TLD change, new domain not working via custom newznab provider list

### ISSUE THREAD

**Issue by treyturner** [gboudreau/sabconnectplusplus#198]
omgwtfnzbs recently announced a TLD change. I tried to add the new domain to the custom Newznab Providers list in SABconnect++ and made sure 'Enable Automatic Newznab Detection' is checked, but the one-click download icons aren't appearing, nor is the 'Send to SABnzbd' on the cart view. I also tried unchecking the checkbox next to omgwtfnzbs in SABconnect++ provider settings in case it was interfering, but it didn't help.

Not sure why the custom Newznab Provider list isn't working, but in any case it seems you'll need to update omgwtfnzbs references to the new TLD. The old domain will become unresolvable on October 20.

**Comment by gboudreau** [comment]
Was handled already here : https://github.com/gboudreau/sabconnectplusplus/pull/197
Still pending Google approval to be available to all.

**Comment by treyturner** [comment]
Just noticed as soon as I submitted, thanks for the quick turnaround and sorry I missed it

**Comment by treyturner** [comment]
Btw the README still references the old TLD
