### ISSUE TITLE
This extension may soon no longer be supported because it doesn't follow best practices for Chrome extensions. ￼ Learn more

### ISSUE THREAD

**Issue by brianjmurrell** [gboudreau/sabconnectplusplus#205]
Any idea what this warning:

![image](https://github.com/user-attachments/assets/fea06ea0-798a-4306-b12b-569bf3b7a646)

means?

**Comment by jdart** [comment]
All chrome extensions need to migrate to "manifest v3" https://github.com/gboudreau/sabconnectplusplus/issues/202

**Comment by brianjmurrell** [comment]
I see.  Thanks very much for the informative pointer.  No need to keep this issue open then.
